### ISSUE TITLE
update period/conditions

### ISSUE THREAD

**Issue by Sigi-cz** [oznu/docker-cloudflare-ddns#34]
not really an issue ...
could You please describe in the readme what is the dns update period / conditions?

**Comment by StrictLine** [comment]
I'd also appreciate it, because I guess at the moment, it's hard coded, right?
**root/etc/services.d/crond/run**: /usr/sbin/crond -f -l 8 -d 6
- runs in the foregrund
- log level 8
- log level 6 (stderr)
... but I haven't found the crontabs yet.

I'm new to the docker, that's why I cannot make you a solution proposal/PR.

**Comment by Sigi-cz** [comment]
based on this #11 it runs every 5 minutes (and it does) but it would be nice to have it in README.md so users don't need to search closed issues for that info.

**Comment by StrictLine** [comment]
You're right, thanks for refering! This should be the permalink for the line where this is set up:
https://github.com/oznu/docker-cloudflare-ddns/blob/3d19e54c211b9ccbf8546900da41b56c262962b9/root/etc/cont-init.d/30-cloudflare-setup#L91

**Comment by StrictLine** [comment]
it'd be more elegant to define an environment variable instead of the hard-coded 5.

**Comment by ghzgod** [comment]
> it'd be more elegant to define an environment variable instead of the hard-coded 5.

I agree with this, for now I edited it using crontab -e command and changing it to 10.  I too would like an environment variable to set the interval.

**Comment by Dulanic** [comment]
Submitted a PR for that a ability to customize. We'll see if accepted. Also would then document the default.
